name: E-Commerce Frontend CI/CD
on:
  pull_request:
    branches:
      - main
    types:
      - closed
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Docker login
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Decode k8s config
        run: |
          echo "${{ secrets.KUBECONFIG_B64 }}" | base64 --decode > kubeconfig
          export KUBECONFIG=$PWD/kubeconfig
        env:
          KUBECONFIG: ${{ github.workspace }}/kubeconfig

      - name: Build and Push Docker image
        run: |
          docker build --build-arg NEXT_PUBLIC_BACKEND_URL=${{ secrets.BACKEND_URL }} --build-arg JWT_SECRET=${{ secrets.JWT_SECRET }} -t ${{ secrets.ACR_LOGIN_SERVER }}/ecommerce_frontend:${{ github.sha }} .
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/ecommerce_frontend:${{ github.sha }}

      - name: Deploy to Kubernetes
        env:
          KUBECONFIG: ${{ github.workspace }}/kubeconfig
        run: |
          kubectl set image deployment/ecommerce-frontend-deployment frontend=${{ secrets.ACR_LOGIN_SERVER }}/ecommerce_frontend:${{ github.sha }}
          kubectl rollout status deployment/ecommerce-frontend-deployment
